[variables]
# Node.js version
NODE_VERSION = "20"
# Port for the application
PORT = "4000"
# Environment
NODE_ENV = "production"

[phases.setup]
# Install Node.js and system dependencies
nixpkgs = ["nodejs_20", "npm", "curl", "bash"]

[phases.install]
# Install dependencies
cmds = [
  "npm ci --omit=dev",
  # Install Encore CLI
  "curl -L https://encore.dev/install.sh | bash",
  # Add Encore to PATH
  "export PATH=\"$HOME/.encore/bin:$PATH\""
]

[phases.build]
# Build the Next.js application and Encore backend
cmds = [
  "npm run build",
  # Build Encore application if needed
  "export PATH=\"$HOME/.encore/bin:$PATH\" && encore build docker --config ./infra.json pos:latest || echo 'Encore build skipped'"
]

[phases.start]
# Start the application
cmd = "npm start"

[providers.vercel]
# Vercel-specific configuration
framework = "nextjs"

[providers.railway]
# Railway-specific configuration
builder = "nixpacks"

[providers.render]
# Render-specific configuration
build_command = "npm run build"
start_command = "npm start"

# Environment-specific overrides
[phases.install.env]
NPM_CONFIG_PRODUCTION = "false"

[phases.build.env]
NODE_ENV = "production"

[phases.start.env]
PORT = "4000"
NODE_ENV = "production"